/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/FormActionBar.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

export {FormActionBar};

declare namespace UiElements {

  /**
   * The `<form-action-bar>` renders an action buttons and status information in the bottom of the form.
   *
   * ```html
   * <form is="iron-form">
   *   <form-action-bar>
   *     <div id="status" slot="prefix">Form status OK</div>
   *     <paper-button>cancel</paper-button>
   *     <paper-button>save</paper-button>
   *   </form-action-bar>
   * </form>
   * ```
   *
   * Children are rendered on the right hand side of the bar.
   *
   * If a child element contains a `slot="prefix"` attribute it will be
   * rendered on the left hand side of the bar.
   *
   * ### Parent container padding
   *
   * Parent container should have  bottom padding at least the same as the `--form-action-bar-height` CSS variable value.
   * By default it is 64 pixels. The bar reders itself in fixed position so everything behind it is not visible.
   *
   * ### Elevation
   *
   * Use the `elevation` attribute (in range 0-8) to set z-deepth of the
   * bar were 0 is no elevation at all and 8 is to highest elevation.
   * Default elevation is 1.
   *
   * ### Styling
   *
   * `<form-action-bar>` provides the following custom properties and mixins for styling:
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--form-action-bar-background` | Background color of the bar | `#fff`
   * `--form-action-bar-height` | Bar height | `64px`
   * `--form-action-bar-content` | Mixin applied to the main container (excluding prefixes) | `{}`
   */
  class FormActionBar extends HTMLElement {
    elevation: any;
    connectedCallback(): void;
  }
}
